version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: garage-php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environnement:
      - DB_HOST-db
      - DB_NAME-${DB_NAME}
      - DB_USER-${DB_USER}
      - DB_PASSWORD-${DB_PASSWORD}
      - STORAGE_PATH=/var/www/html/storage

  db:
    image: mysql:8.0
    container_name: garagephp-db
    restart: unless-stopped
    environnement:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:        
               